"""
Django settings for euphorbia project.

Generated by 'django-admin startproject' using Django 1.8.1.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

STATIC_ROOT = os.path.join(BASE_DIR, 'static_root')
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '0x!#&$#1l$1y0(*!0*t-y&-qoyl#34sq()7^6lyu&d_5dpjs57'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'platform',
    'users',
    'django.contrib.humanize'
)

MIDDLEWARE_CLASSES = (
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
)

ROOT_URLCONF = 'euphorbia.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.dirname(__file__), 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'euphorbia.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        # Add 'postgresql_psycopg2', 'mysql', 'sqlite3' or 'oracle'.
        'NAME': 'postgres',  # Or path to database file if using sqlite3.
        # The following settings are not used with sqlite3:
        'USER': 'postgres',
        #'USER': 'django',
        'PASSWORD': 'password',
        #'PASSWORD': 'ooFxfq111',
        'HOST': 'px.adbox.kz',  # Empty for localhost through domain sockets or '127.0.0.1' for localhost through TCP.
        'PORT': '5445',  # Set to empty string for default.
    }
}


# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Inner security constants
CHALLENGE_RANGE = '0123456789abcdef'
CHALLENGE_LENGTH = 40
SERVER_SECRET = [16,32,17,33,14,8,24,39,13,11,2,9,29,21,1,3,10,26,25,27]
CLIENT_SECRET_RES = [14,35,29,15,7,4,12,22,0,36,21,33,11,26,31,23,5,1,17,8]
CLIENT_SECRET_KEY = [2,3,6,9,10,13,16,18,19,20,24,25,27,28,30,32,34,37,38,39]

CLIENT_SECRET_KEY = [2,3,6,9,10,13,16,18,19,20,24,25,27,28,30,32,34,37,38,39]


AUTH_PROFILE_MODULE = 'users.User'  # custom user
AUTH_USER_MODEL = 'users.User'  # custom user

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/
STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
    os.path.join(BASE_DIR, "platform","static"),
    os.path.join(BASE_DIR, "media"),
]

import django.contrib.auth

django.contrib.auth.LOGIN_URL = "/platform/login/"
LOGIN_URL = "/platform/login/"
LOGIN_REDIRECT_URL = "/platform/profile/"